In [1]:
import mysql.connector
import pandas as pd
from mysql.connector import connect, errorcode
import matplotlib.pyplot as plt
import plotly.express as px
import folium
import geopandas as gpd
import numpy as np

In [2]:
from sqlalchemy import create_engine, text
user = 'root'
password = '20mnUXN5N5'
host = 'localhost'
database = 'Data'

# Create an SQLAlchemy engine
engine = create_engine(f'mysql+mysqlconnector://{user}:{password}@{host}/{database}')
sql_query = "SELECT * FROM shootingsottawa order by ID"

with engine.connect() as conn:
    df = pd.read_sql(text(sql_query), con=conn)

In [3]:
df.shape

(456, 20)

In [4]:
df

,ID,Reported_Date,Reported_Hour,Reported_Year,Occurred_Date,Occurred_Hour,Occurred_Year,Time_of_Day,Weekday,Day_of_Week,Neighbourhood,Sector,Division,Ward,Councillor,Census_Tract,Level_of_Injury,x,y,Occurred_Month
0,1,2018-01-03 05:00:00,200,2018,2018-01-03 05:00:00,2200,2018,Evening,Wednesday,3,Elmvale - Eastway - Riverview - Riverview Park...,33,East,Ward 18 - Alta Vista,Marty Carr,5050008.00,UNKNOWN,-75.621874,45.388197,January
1,2,2018-01-05 05:00:00,1900,2018,2018-01-05 05:00:00,1900,2018,Evening,Friday,5,Overbrook - McArthur,25,Central,Ward 13 - Rideau-Rockcliffe,Rawlson King,5050012.00,UNKNOWN,-75.647223,45.426179,January
2,3,2018-01-05 05:00:00,100,2018,2018-01-04 05:00:00,2300,2018,Evening,Thursday,4,West Centertown,22,Central,Ward 14 - Somerset,Ariel Troster,5050042.00,MAJOR,-75.710548,45.406629,January
3,4,2018-01-09 05:00:00,200,2018,2018-01-09 05:00:00,2000,2018,Evening,Tuesday,2,Hunt Club East - Western Community,35,East,Ward 16 - River,Riley Brockington,5050002.05,FATAL,-75.674849,45.349145,January
4,5,2018-01-10 05:00:00,1900,2018,2018-01-10 05:00:00,1900,2018,Evening,Wednesday,3,Rockcliffe - Manor Park,25,Central,Ward 13 - Rideau-Rockcliffe,Rawlson King,5050059.00,UNKNOWN,-75.652362,45.450809,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,452,2024-11-18 05:00:00,1800,2024,2024-11-18 05:00:00,1800,2024,Evening,Monday,1,East Industrial,33,East,Ward 18 - Alta Vista,Marty Carr,5050011.01,UNKNOWN,-75.640310,45.410579,November
452,453,2024-11-23 05:00:00,800,2024,2024-11-22 05:00:00,2100,2024,Evening,Friday,5,Woodroffe - Lincoln Heights,14,West,Ward 7 - Bay,Theresa Kavanagh,5050031.00,UNKNOWN,-75.782107,45.371607,November
453,454,2024-12-04 05:00:00,0,2024,2024-12-04 05:00:00,0,2024,Night,Wednesday,3,Riverside Park,34,East,Ward 16 - River,Riley Brockington,5050003.00,MAJOR,-75.687771,45.369605,December
454,455,2024-12-31 05:00:00,800,2024,2024-12-31 05:00:00,800,2024,Morning,Tuesday,2,Glebe - Dows Lake,22,Central,Ward 17 - Capital,Shawn Menard,5050036.00,NONE,-75.696378,45.403246,December
455,456,2024-12-31 05:00:00,1400,2024,2024-12-31 05:00:00,1400,2024,Afternoon,Tuesday,2,Lowertown,24,Central,Ward 12 - Rideau-Vanier,StZphanie Plante,5050056.00,UNKNOWN,-75.684454,45.434410,December

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 456 entries, 0 to 455
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               456 non-null    int64
 1   Reported_Date    456 non-null    datetime64[ns]
 2   Reported_Hour    456 non-null    int64
 3   Reported_Year    456 non-null    int64
 4   Occurred_Date    456 non-null    datetime64[ns]
 5   Occurred_Hour    456 non-null    int64
 6   Occurred_Year    456 non-null    int64
 7   Time_of_Day      456 non-null    object
 8   Weekday          456 non-null    object
 9   Day_of_Week      456 non-null    int64
 10  Neighbourhood    456 non-null    object
 11  Sector           456 non-null    int64
 12  Division         456 non-null    object
 13  Ward             456 non-null    object
 14  Councillor       456 non-null    object
 15  Census_Tract     456 non-null    float64
 16  Level_of_Injury  456 non-null    object
 17  x                456 non-null    float64
 18  y                456 non-null    float64
 19  Occurred_Month   456 non-null    object
dtypes: datetime64[ns](2), float64(3), int64(7), object(8)
memory usage: 71.4+ KB

In [6]:
df[['Level_of_Injury']].value_counts()

Level_of_Injury
UNKNOWN            176
MAJOR              100
NONE                91
MINOR               61
FATAL               27
NOT APPLICABLE       1
dtype: int64

In [8]:
lat = 45.25 
long = -75.8
ottawa_map = folium.Map(location=[lat, long], zoom_start=9.5, width=800, height=600)

# display the map of Ottawa
ottawa_map

In [9]:
ward_layer  = 'https://open.ottawa.ca/datasets/ottawa::wards-2022-2026.geojson'
folium.GeoJson(ward_layer).add_to(ottawa_map)

In [11]:
ottawa_map

In [18]:
folium.GeoJson(
    ward_layer,
    name='Wards of Ottawa',
    style_function=lambda feature: {
        'fillColor': '#228B22',  # Green color
        'color': 'black',
        'weight': 1,
        'fillOpacity': 0.25
    }
).add_to(ottawa_map)

In [19]:
ottawa_map

In [20]:
df[['Level_of_Injury','Councillor', 'Neighbourhood','y', 'x']]

,Level_of_Injury,Councillor,Neighbourhood,y,x
0,UNKNOWN,Marty Carr,Elmvale - Eastway - Riverview - Riverview Park...,45.388197,-75.621874
1,UNKNOWN,Rawlson King,Overbrook - McArthur,45.426179,-75.647223
2,MAJOR,Ariel Troster,West Centertown,45.406629,-75.710548
3,FATAL,Riley Brockington,Hunt Club East - Western Community,45.349145,-75.674849
4,UNKNOWN,Rawlson King,Rockcliffe - Manor Park,45.450809,-75.652362
...,...,...,...,...,...
451,UNKNOWN,Marty Carr,East Industrial,45.410579,-75.640310
452,UNKNOWN,Theresa Kavanagh,Woodroffe - Lincoln Heights,45.371607,-75.782107
453,MAJOR,Riley Brockington,Riverside Park,45.369605,-75.687771
454,NONE,Shawn Menard,Glebe - Dows Lake,45.403246,-75.696378
455,UNKNOWN,StZphanie Plante,Lowertown,45.434410,-75.684454

In [23]:
# instantiate a feature group for the incidents in the dataframe
incident = folium.map.FeatureGroup()

# loop through the shootings and add each to the incidents feature group
for lat, lng, label, label1,label2, label3  in zip(df.y, df.x, df['Neighbourhood'], \
                                           df['Councillor'], df['Occurred_Year'], df['Level_of_Injury']):
    
    
    # Format the popup content with HTML
    popup_content = f"""
    <div>
        <strong>Neighbourhood:</strong> {label}<br>
        <strong>Councillor:</strong> {label1}<br>
        <strong>Occurred Year:</strong> {label2}<br>
        <strong>Level of Injury':</strong> {label3}<br>
    </div>
    """
    

    incident.add_child(
        folium.vector_layers.CircleMarker(
            [lat, lng],
            radius=5, # define how big you want the circle markers to be
            #color='yellow',
            popup = folium.Popup(popup_content, max_width=300),
            fill=True,
            fill_color='blue',
            fill_opacity=0.6
        )
    )

# add incidents to map
ottawa_map.add_child(incident)

In [24]:
df_peryear = df[df['Occurred_Year'] == 2023]
df_peryear.head(20)

,ID,Reported_Date,Reported_Hour,Reported_Year,Occurred_Date,Occurred_Hour,Occurred_Year,Time_of_Day,Weekday,Day_of_Week,Neighbourhood,Sector,Division,Ward,Councillor,Census_Tract,Level_of_Injury,x,y,Occurred_Month
339,340,2023-01-07 05:00:00,1900,2023,2023-01-07 05:00:00,1900,2023,Evening,Saturday,6,Carlington,21,Central,Ward 16 - River,Riley Brockington,5050022.00,UNKNOWN,-75.735979,45.373741,January
340,341,2023-01-13 05:00:00,1600,2023,2023-01-13 05:00:00,1600,2023,Afternoon,Friday,5,Civic Hospital-Central Park,21,Central,Ward 15 - Kitchissippi,Jeff Leiper,5050034.00,MAJOR,-75.728858,45.396000,January
341,342,2023-01-19 05:00:00,1900,2023,2023-01-19 05:00:00,1900,2023,Evening,Thursday,4,Centretown,23,Central,Ward 14 - Somerset,Ariel Troster,5050038.00,MINOR,-75.693770,45.415563,January
342,343,2023-01-29 05:00:00,0,2023,2023-01-29 05:00:00,0,2023,Night,Sunday,7,Emerald Woods - Sawmill Creek,35,East,Ward 10 - Gloucester-Southgate,Jessica Bradley,5050123.01,MINOR,-75.647478,45.348935,January
343,344,2023-01-29 05:00:00,200,2023,2023-01-29 05:00:00,200,2023,Night,Sunday,7,Elmvale - Eastway - Riverview - Riverview Park...,33,East,Ward 18 - Alta Vista,Marty Carr,5050011.04,MINOR,-75.650153,45.405726,January
344,345,2023-02-14 05:00:00,1800,2023,2023-02-14 05:00:00,1800,2023,Evening,Tuesday,2,Elmvale - Eastway - Riverview - Riverview Park...,33,East,Ward 18 - Alta Vista,Marty Carr,5050011.04,FATAL,-75.653355,45.409261,February
345,346,2023-02-18 05:00:00,200,2023,2023-02-18 05:00:00,2000,2023,Evening,Saturday,6,Crestview - Meadowlands,17,West,Ward 8 - College,Laine Johnson,5050133.00,NONE,-75.745262,45.355661,February
346,347,2023-02-18 05:00:00,200,2023,2023-02-18 05:00:00,2200,2023,Evening,Saturday,6,Lowertown,24,Central,Ward 12 - Rideau-Vanier,StZphanie Plante,5050056.00,NONE,-75.685641,45.433918,February
347,348,2023-02-21 05:00:00,100,2023,2023-02-21 05:00:00,100,2023,Night,Tuesday,2,Lowertown,24,Central,Ward 12 - Rideau-Vanier,StZphanie Plante,5050056.00,FATAL,-75.687315,45.430420,February
348,349,2023-02-27 05:00:00,200,2023,2023-02-27 05:00:00,1900,2023,Evening,Monday,1,Emerald Woods - Sawmill Creek,35,East,Ward 10 - Gloucester-Southgate,Jessica Bradley,5050123.01,NONE,-75.650782,45.349036,February
349,350,2023-02-27 05:00:00,200,2023,2023-02-27 05:00:00,2000,2023,Evening,Monday,1,Overbrook - McArthur,25,Central,Ward 13 - Rideau-Rockcliffe,Rawlson King,5050012.00,UNKNOWN,-75.651444,45.426607,February
350,351,2023-03-04 05:00:00,200,2023,2023-03-04 05:00:00,2100,2023,Evening,Saturday,6,Crestview - Meadowlands,17,West,Ward 8 - College,Laine Johnson,5050134.00,UNKNOWN,-75.733964,45.345193,March
351,352,2023-03-05 05:00:00,700,2023,2023-03-05 05:00:00,700,2023,Morning,Sunday,7,OrlZans Village - Chateauneuf,31,East,Ward 2 - OrlZans West-Innes,Laura Dudas,5050125.08,MINOR,-75.504778,45.455701,March
352,353,2023-03-17 05:00:00,900,2023,2023-03-17 05:00:00,900,2023,Morning,Friday,5,Greenbelt - Stony Swamp,15,West,Ward 8 - College,Laine Johnson,5050141.14,UNKNOWN,-75.822814,45.304484,March
353,354,2023-04-03 05:00:00,300,2023,2023-04-03 05:00:00,300,2023,Night,Monday,1,Greenboro East,35,East,Ward 10 - Gloucester-Southgate,Jessica Bradley,5050001.05,MAJOR,-75.642810,45.363109,April
354,355,2023-04-12 05:00:00,1900,2023,2023-04-12 05:00:00,1900,2023,Evening,Wednesday,3,Riverside South - Leitrim,35,East,Ward 22 - Riverside South-Findlay Creek,Steve Desroches,5050126.07,NONE,-75.617370,45.309418,April
355,356,2023-04-16 05:00:00,1800,2023,2023-04-15 05:00:00,1400,2023,Afternoon,Saturday,6,Rothwell Heights - Beacon Hill North,32,East,Ward 11 - Beacon Hill-Cyrville,Tim Tierney,5050121.01,UNKNOWN,-75.594196,45.447348,April
356,357,2023-04-22 05:00:00,400,2023,2023-04-22 05:00:00,400,2023,Night,Saturday,6,Byward Market,24,Central,Ward 12 - Rideau-Vanier,StZphanie Plante,5050054.00,MINOR,-75.691761,45.429606,April
357,358,2023-04-24 05:00:00,1500,2023,2023-04-24 05:00:00,1500,2023,Afternoon,Monday,1,West Centertown,22,Central,Ward 14 - Somerset,Ariel Troster,5050041.00,NONE,-75.705612,45.409315,April
358,359,2023-04-24 05:00:00,1900,2023,2023-04-24 05:00:00,1900,2023,Evening,Monday,1,OrlZans Avalon - Notting Gate - Fallingbrook -...,31,East,Ward 19 - OrlZans South-Navan,Catherine Kitts,5050171.07,MINOR,-75.462611,45.465927,April

In [25]:
df_peryear.shape

(74, 20)

In [26]:
df_peryear[['Occurred_Year', 'Ward','Level_of_Injury','Councillor', 'Neighbourhood','y', 'x']]

,Occurred_Year,Ward,Level_of_Injury,Councillor,Neighbourhood,y,x
339,2023,Ward 16 - River,UNKNOWN,Riley Brockington,Carlington,45.373741,-75.735979
340,2023,Ward 15 - Kitchissippi,MAJOR,Jeff Leiper,Civic Hospital-Central Park,45.396000,-75.728858
341,2023,Ward 14 - Somerset,MINOR,Ariel Troster,Centretown,45.415563,-75.693770
342,2023,Ward 10 - Gloucester-Southgate,MINOR,Jessica Bradley,Emerald Woods - Sawmill Creek,45.348935,-75.647478
343,2023,Ward 18 - Alta Vista,MINOR,Marty Carr,Elmvale - Eastway - Riverview - Riverview Park...,45.405726,-75.650153
...,...,...,...,...,...,...,...
408,2023,Ward 8 - College,FATAL,Laine Johnson,Centrepointe,45.346090,-75.770546
409,2023,Ward 11 - Beacon Hill-Cyrville,UNKNOWN,Tim Tierney,Beacon Hill South - Cardinal Heights,45.445502,-75.593995
410,2023,Ward 13 - Rideau-Rockcliffe,MINOR,Rawlson King,CFB Rockcliffe-NRC,45.439988,-75.646214
411,2023,Ward 7 - Bay,MAJOR,Theresa Kavanagh,Whitehaven - Queensway Terrace North,45.354739,-75.801110
412,2023,Ward 9 - Knoxdale-Merivale,MINOR,Sean Devine,Hunt Club South Industrial,45.333795,-75.717264

In [27]:

ottawa_map1 = folium.Map(location=[lat, long], zoom_start=9)
ottawa_map1

In [30]:
folium.GeoJson(
    ward_layer,
    name='Wards of Ottawa',
    style_function=lambda feature: {
        'fillColor': '#228B22',  # Green color
        'color': 'black',
        'weight': 1,
        'fillOpacity': 0.25
    }
).add_to(ottawa_map1)

In [31]:
ottawa_map1

In [32]:
# instantiate a feature group for the incidents in the dataframe
incident1 = folium.map.FeatureGroup()

# loop through the shootings and add each to the incidents feature group
for lat, lng, label, label1,label2, label3  in zip(df_peryear.y, df_peryear.x, df_peryear['Neighbourhood'], \
                                           df_peryear['Councillor'], df_peryear['Occurred_Year'], df_peryear['Level_of_Injury']):
    
    
    # Format the popup content with HTML
    popup_content = f"""
    <div>
        <strong>Neighbourhood:</strong> {label}<br>
        <strong>Councillor:</strong> {label1}<br>
        <strong>Occurred Year:</strong> {label2}<br>
        <strong>Level of Injury':</strong> {label3}<br>
    </div>
    """
    

    incident1.add_child(
        folium.vector_layers.CircleMarker(
            [lat, lng],
            radius=5, # define how big you want the circle markers to be
            color='yellow',
            popup = folium.Popup(popup_content, max_width=300),
            fill=True,
            fill_color='blue',
            fill_opacity=0.6
        )
    )

# add incidents to map
ottawa_map1.add_child(incident1)

In [33]:
ottawa_map1